sudo: required
notifications:
  email: false
language: java
jdk:
- oraclejdk8
os:
- linux
services:
- docker
env:
- MONGOLASTIC_FULL="ozlerhakan/mongolastic:1.3.15"
- MONGOLASTIC_SHORT="ozlerhakan/mongolastic:1.3"
script: mvn install
before_install:
- whereis elasticsearch
- curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.3.deb
- sudo service elasticsearch start
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
- echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
- sudo apt-get update
- sudo apt-get install -y --force-yes mongodb-org=3.2.10 mongodb-org-server=3.2.10 mongodb-org-tools=3.2.10
- sudo service mongod start
- mongod --version
before_script:
- wget https://dl.dropboxusercontent.com/u/15056258/mongodb/tweets.zip
- unzip tweets.zip
- sleep 15
- curl http://localhost:9200/
- mongorestore -h 127.0.0.1 --port 27017 dump
- mvn clean
after_success:
- docker version
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker build -t $MONGOLASTIC_FULL .;
  docker tag $MONGOLASTIC_FULL $MONGOLASTIC_SHORT;
  docker images;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push $MONGOLASTIC_FULL;
  docker push $MONGOLASTIC_SHORT;
  fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: E8iX+y1svn/88ftT5fnMIfECNUNek0T/VtrkdacuFriC/cNcopcZUuIEqmCTuMIvo+iL/h4F4wYzGLadRU6iOhnPk8oMPadcR+2Pll/mz7/I4zcj/iZL8KMJGlJxLpnTKBw3QEGnWflg/S8I6g6bOcGnPhQW0AQZ6bj7FBR59Gd7abtqAkwZVki+zxXbMzMqA3VYRaMc2UEdTU6AlcR7GeCdcDFhQ/4uqmMySGGGKLAROZ+0r9BhbaZ0ivuR7Uza9l68d0FhN2wRxDhP86RM3hbZttGQw+CBw7+3IcHoJ9MpSGgatxWd3eudWypDoocVs9FxYKS3zJcVzzLWtmB1yRdY/zOcLkr7Tkz2z+LIZbjPJFjeDUgpRJPqw8ckPOEbsdmp+/0zVBp+aDdMgpa3hfXkchTa4hXUDWJCZiuN4oByWxnBqoALUAjRdIflCeZuukbmHzZb6QWNTfRSGAZtQHO+sdJIvMFFC9v0k6T2WXvlEWDXt0cA8Gid9iBZLZfemJiBRNRP94TDcakMZzwnBH/G3l1nc7tk8AR7gX0b/biLeloSdxdI7UGV+uLvy+LgrsJp5TeLvBaylCRJ6672IvroGZwZm/GG3NsPS1vb2WoZfbjiS+paWUxreeFumJyg43Vuv0LiDND2y2P8zTtnC7HaM0k54ewt86Kx5w86Ma0=
  file: /home/travis/build/ozlerhakan/mongolastic/target/mongolastic.jar
  on:
    tags: true
    all_branches: true
    repo: ozlerhakan/mongolastic

